---
- name: Create init directory
  file:
    path: "{{ aws_sf_init_dir_scripts }}"
    state: directory

- name: Copy ansible dir to remote
  synchronize:
    delete: "yes"
    src: "{{ playbook_dir }}/../.."
    dest: "{{ aws_sf_init_dir_ansible }}"

- name: Copy init script to remote server
  template:
    src: init.j2
    dest: "{{ aws_sf_init_script }}"
    owner: root
    group: root
...
